### ISSUE TITLE
Pretraining config/code

### ISSUE THREAD

**Issue by muntasir2000** [AUGMXNT/shisa#1]
Thank you for sharing your work. This is great. I am also trying to do similar things for Bengali language. Can you please share how you ran pretraining with the updated tokenizer? Any code or config will be great. 

Also, we are looking for collaborators for building the first open source Bengali LLM, on top of Gemma or Mistral. If you want to collaborate, we'd be happy to have you onboard.

**Comment by lhl** [comment]
Hi sorry, have been busy and missed this. I'll see if I can dig up the code from my archives. Will try to do a better job w/ shisa-v2 repo. For using the updated tokenizer you can just drop it in, but I'd recommend taking a look at for an interesting new technique: https://github.com/bminixhofer/zett

I'm pretty busy w/ shisa-v2 and other projects now, but good luck w/ your project, the more multi-lingual open LLMs the better!
